#ifndef SOURCE_SENSORPARAMETERS_H_
#define SOURCE_SENSORPARAMETERS_H_

#include "XDK_Utils.h"

#define APP_CONTROLLER_TX_DELAY             UINT32_C(30000)

#define APP_TEMPERATURE_OFFSET_CORRECTION   (-3459)

#define APP_CURRENT_RATED_TRANSFORMATION_RATIO      (0)

#endif /* SOURCE_SENSORPARAMETERS_H_ */
